[HELP]
en = """
**BillBuddy Service Menu**

ğŸ“² **Buy Airtime/Data**  
Purchase airtime or data for any network easily.

ğŸ’¡ **Pay Bills**  
Settle your utility bills quickly and securely.

ğŸ’¸ **Transfer Funds**  
Effortlessly transfer money to other users.

ğŸ“Š **Transaction History**  
View detailed records of all your transactions.

ğŸ’³ **Check Balance**  
Instantly check your VTU wallet balance.

ğŸ **Promotions**  
Discover and take advantage of exclusive promotions.

âš™ï¸ **Account Settings**  
Manage and update your account settings.

â“ **Help**  
Find answers to common questions and get help.

ğŸ‘¥ **Referral Program**  
Invite friends and earn rewards for referrals.


â‚¿ **Crypto Payments**  
Make payments using cryptocurrency.

ğŸŒ **Multi-Language Support**  
Switch to your preferred language for convenience.


ğŸ”— **One-Click Payment**  
generate link and send to a user to receive quick payment

---
"""
es = """
**MenÃº de servicios de BillBuddy**

ğŸ“² **Comprar tiempo aire/datos**
Comprar tiempo aire o datos para cualquier red fÃ¡cilmente.
**MenÃº de servicios de BillBuddy**

ğŸ“² **Comprar tiempo aire/datos**
Comprar tiempo aire o datos para cualquier red fÃ¡cilmente.
**BillBuddy Services Menu**

ğŸ“² **Buy Airtime/Data**
Buy airtime or data for any network easily.
**MenÃº de servicio BillBuddy**

ğŸ“² **Comprar tiempo aire/datos**
Compra tiempo aire o datos para cualquier red fÃ¡cilmente.
**BillBuddy Service Menu**

ğŸ“² **Buy Airtime/Data**
Buy airtime or data for any network easily.
**MenÃº de servicio de BillBuddy**

ğŸ“² **Comprar Tiempo Aire/Datos**
Compra fÃ¡cilmente tiempo aire o datos para cualquier red.
**BillBuddy Service Menu**

ğŸ“² **Buy Airtime/Data**
Easily purchase airtime or data for any network.


ğŸ’¡ **Pagar facturas**
Liquida tus facturas de servicios pÃºblicos de forma rÃ¡pida y segura.

ğŸ’¸ **Transferir fondos**
Transfiere dinero sin esfuerzo a otros usuarios.

ğŸ“Š **Historial de transacciones**
Ve registros detallados de todas tus transacciones.

ğŸ’³ **Consultar saldo**
Consulta al instante el saldo de tu billetera VTU.

ğŸ **Promociones**
Descubre y aprovecha promociones exclusivas.

âš™ï¸ **ConfiguraciÃ³n de la cuenta**
Administra y actualiza la configuraciÃ³n de tu cuenta.

â“ **Ayuda**
Encuentra respuestas a preguntas frecuentes y obtÃ©n ayuda.

ğŸ‘¥ **Programa de referencias**
Invita a tus amigos y gana recompensas por referencias.

â‚¿ **Pagos con criptomonedas**
Realice pagos con criptomonedas.

ğŸŒ **Compatibilidad con varios idiomas**
Cambie a su idioma preferido para mayor comodidad.

ğŸ”— **Pago con un solo clic**
Genere un enlace y envÃ­elo a un usuario para recibir un pago rÃ¡pido

---
Send feedback
Translation results available 

"""