[KEYBOARDS]

en = {"buttons"= [ "ğŸ“² Buy Airtime/Data","ğŸ’¡ Pay Bills","ğŸ’¸ Transfer Funds","ğŸ“Š Transaction History","ğŸ’³ Check Balance","ğŸ Promotions","âš™ï¸ Account Settings","â“ Help","ğŸ‘¥ Referral Program","â‚¿ Crypto Payments","ğŸŒ Multi-Language Support","ğŸ”— One-Click Payment"],"headers"= "ğŸ’³ Check Balance", "footers"= ["ğŸŒ Multi-Language Support", "â“ Help","âš™ï¸ Account Settings"]}

es = {"buttons"= [ "ğŸ“² Comprar tiempo aire/datos","ğŸ’¡ Pagar facturas","ğŸ’¸ Transferir fondos","ğŸ“Š Historial de transacciones","ğŸ’³ Consultar saldo","ğŸ Promociones","âš™ï¸ ConfiguraciÃ³n de cuenta","â“ Ayuda","ğŸ‘¥ Programa de referencias","â‚¿ Pagos criptogrÃ¡ficos" ,"ğŸŒ Soporte multilingÃ¼e","ğŸ”— Pago con un clic"],"headers"= " ğŸ’³ Consultar saldo", "footers"= ["ğŸŒ Soporte multilingÃ¼e", "â“ Ayuda","âš™ï¸ ConfiguraciÃ³n de cuenta"]}

[MESSAGE]
en = "ğŸ˜ Main Menu"
es = "ğŸ˜ MenÃº principals"