[START]
en =  """
**Hey there, {}! ğŸ‰ Welcome to BillBuddy!**

We're thrilled to have you on board. ğŸŒŸ To get started, please choose your preferred language from the list below. This will help us make your experience as smooth and enjoyable as possible.

Select your language and letâ€™s dive in! ğŸš€
"""

[KEYBOARDS]
en= ["ğŸ‡¬ğŸ‡§ English","ğŸ‡ªğŸ‡¸ Spanish"]

