[START]
en =  """
**Hey there, {}! ğŸ‰ Welcome to BillBuddy!**

To get started, please choose your preferred language from the list below. This will help us make your experience as smooth and enjoyable as possible.
"""

[KEYBOARDS]
en= {"ğŸ‡¬ğŸ‡§ English"="en","ğŸ‡ªğŸ‡¸ Spanish"="es"}
es = {"ğŸ‡¬ğŸ‡§ Englash"="en","ğŸ‡ªğŸ‡¸ Espanol"="es"}
